-- ================================================
-- Template generated from Template Explorer using:
-- Create Procedure (New Menu).SQL
--
-- Use the Specify Values for Template Parameters 
-- command (Ctrl-Shift-M) to fill in the parameter 
-- values below.
--
-- This block of comments will not be included in
-- the definition of the procedure.
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Jose Maria Muñoz Huaman
-- Create date: 06/08/2020
-- Description:	Insertar nuevos valores de Prometeo Pagado Antegrado
-- =============================================
CREATE PROCEDURE  [dbo].[Proc_InsertarNuevosValoresDeBasePrometeoPagadoAnt]
	-- Add the parameters for the stored procedure here
	  
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	--SET NOCOUNT ON;

    -- Insert statements for procedure here

INSERT INTO [dbo].[tb_prometeo_pagado_antegrado]
           ([N°]
           ,[Id Sisproven]
           ,[Id Campus Evolution]
           ,[Modalidad Inicial]
           ,[sub modalidad incial]
           ,[Modalidad Final]
           ,[Sub modalidad Final]
           ,[Fecha de Procedencia]
           ,[Fecha de Pago]
           ,[Cuanto pago por modalidad]
           ,[Apellidos]
           ,[Nombres]
           ,[Género]
           ,[Carrera]
           ,[Horario]
           ,[Duración]
           ,[Carga Acad#]
           ,[N° Unid# Acad#]
           ,[Escala Inicial]
           ,[Escala Final]
           ,[N° Boletas]
           ,[Valor 1era Boleta]
           ,[Cond# Económica]
           ,[Fecha Recat#]
           ,[Pagantes]
           ,[Fecha Pago de boleta]
           ,[Recogió Cronograma]
           ,[Recogió Horario]
           ,[Fecha Recogió Horario]
           ,[Perdido]
           ,[Fecha de Perdido]
           ,[Motivo Perdido]
           ,[Asesor Inicial]
           ,[Asesor Final]
           ,[Doc# Completos al Inscribirse]
           ,[Sondeo carreras de 3 ó 4 anos]
           ,[Dirección]
           ,[Distrito]
           ,[E-mail]
           ,[Edad]
           ,[Colegio]
           ,[Distrito Colegio]
           ,[Año fin Colegio]
           ,[Pensión Colegio]
           ,[Monto Declarado]
           ,[Otra Institución de Traslado]
           ,[Carrera de procedencia]
           ,[Motivo de traslado]
           ,[File Completo]
           ,[2 fotos tamaño carné]
           ,[Certificado (Original de 1° a 5° de Secundaria)]
           ,[Certificados de los Primeros Puestos (hasta el 5º en toda la sec]
           ,[Constancia de ingreso de Universidad o Instituto de procedencia]
           ,[Constancia de la Federación Nacional de Deporte]
           ,[Copia de DNI o Partida de Nacimiento]
           ,[Syllabus y Certificado de notas Originales de la Institución de ]
           ,[Consentimiento de datos]
           ,[Declaración Jurada]
           ,[Información de Pago del Postulante]
           ,[Solicitud de admisión]
           ,[Traslado]
           ,[Certificado (Original) de 1° a 5° de Secundaria – con promedio i]
           ,[File Completo1]
           ,[Fecha File Completo]
           ,[Fecha pago matrícula]
           ,[Estado Cliente]
           ,[Últ# Contacto]
           ,[Tipo Seguimiento]
           ,[Respuesta]
           ,[Observación]
           ,[Sede Atención]
           ,[Hábil para Pagar]
           ,[Fecha Hábil para Pagar]
           ,[Teléfono]
           ,[Celular]
           ,[Fecha de Procedencia Final]
           ,[Sede Interés]
           ,[Acción]
           ,[Fecha Acción]
           ,[Tipo Contacto]
           ,[Adelanta Curso]
           ,[Asesor registra MyB]
           ,[Adelante Ciclo 0]
           ,[1ra Boleta Fraccionada]
           ,[Observación Colegio]
           ,[Becado 100%]
           ,[Matricula]
           ,[Postulantes]
           ,[Estudio Superior: Univ/Instit]
           ,[Monto Declarado1]
           ,[DNI]
           ,[Promesa Pago]
           ,[NuevoAntiguo]
           ,[Cod# Modular]
           ,[Traslado_LN]
           ,[F_Ent_Cert_1_a_5_Secun]
           ,[Asesor_contacto]
           ,[tipoPrograma]
           ,[Modalidad])

SELECT [N°]
           ,[Id Sisproven]
           ,[Id Campus Evolution]
           ,[Modalidad Inicial]
           ,[sub modalidad incial]
           ,[Modalidad Final]
           ,[Sub modalidad Final]
           ,[Fecha de Procedencia]
           ,[Fecha de Pago]
           ,[Cuanto pago por modalidad]
           ,[Apellidos]
           ,[Nombres]
           ,[Género]
           ,[Carrera]
           ,[Horario]
           ,[Duración]
           ,[Carga Acad#]
           ,[N° Unid# Acad#]
           ,[Escala Inicial]
           ,[Escala Final]
           ,[N° Boletas]
           ,[Valor 1era Boleta]
           ,[Cond# Económica]
           ,[Fecha Recat#]
           ,[Pagantes]
           ,[Fecha Pago de boleta]
           ,[Recogió Cronograma]
           ,[Recogió Horario]
           ,[Fecha Recogió Horario]
           ,[Perdido]
           ,[Fecha de Perdido]
           ,[Motivo Perdido]
           ,[Asesor Inicial]
           ,[Asesor Final]
           ,[Doc# Completos al Inscribirse]
           ,[Sondeo carreras de 3 ó 4 anos]
           ,[Dirección]
           ,[Distrito]
           ,[E-mail]
           ,[Edad]
           ,[Colegio]
           ,[Distrito Colegio]
           ,[Año fin Colegio]
           ,[Pensión Colegio]
           ,[Monto Declarado]
           ,[Otra Institución de Traslado]
           ,[Carrera de procedencia]
           ,[Motivo de traslado]
           ,[File Completo]
           ,[2 fotos tamaño carné]
           ,[Certificado (Original de 1° a 5° de Secundaria)]
           ,[Certificados de los Primeros Puestos (hasta el 5º en toda la sec]
           ,[Constancia de ingreso de Universidad o Instituto de procedencia]
           ,[Constancia de la Federación Nacional de Deporte]
           ,[Copia de DNI o Partida de Nacimiento]
           ,[Syllabus y Certificado de notas Originales de la Institución de ]
           ,[Consentimiento de datos]
           ,[Declaración Jurada]
           ,[Información de Pago del Postulante]
           ,[Solicitud de admisión]
           ,[Traslado]
           ,[Certificado (Original) de 1° a 5° de Secundaria – con promedio i]
           ,[File Completo1]
           ,[Fecha File Completo]
           ,[Fecha pago matrícula]
           ,[Estado Cliente]
           ,[Últ# Contacto]
           ,[Tipo Seguimiento]
           ,[Respuesta]
           ,[Observación]
           ,[Sede Atención]
           ,[Hábil para Pagar]
           ,[Fecha Hábil para Pagar]
           ,[Teléfono]
           ,[Celular]
           ,[Fecha de Procedencia Final]
           ,[Sede Interés]
           ,[Acción]
           ,[Fecha Acción]
           ,[Tipo Contacto]
           ,[Adelanta Curso]
           ,[Asesor registra MyB]
           ,[Adelante Ciclo 0]
           ,[1ra Boleta Fraccionada]
           ,[Observación Colegio]
           ,[Becado 100%]
           ,[Matricula]
           ,[Postulantes]
           ,[Estudio Superior: Univ/Instit]
           ,[Monto Declarado1]
           ,[DNI]
           ,[Promesa Pago]
           ,[NuevoAntiguo]
           ,[Cod# Modular]
           ,[Traslado_LN]
           ,[F_Ent_Cert_1_a_5_Secun]
           ,[Asesor_contacto]
           ,[tipoPrograma]
           ,[Modalidad]
FROM (
	SELECT [N°]
           ,[Id Sisproven]
           ,[Id Campus Evolution]
           ,[Modalidad Inicial]
           ,[sub modalidad incial]
           ,[Modalidad Final]
           ,[Sub modalidad Final]
           ,[Fecha de Procedencia]
           ,[Fecha de Pago]
           ,[Cuanto pago por modalidad]
           ,[Apellidos]
           ,[Nombres]
           ,[Género]
           ,[Carrera]
           ,[Horario]
           ,[Duración]
           ,[Carga Acad#]
           ,[N° Unid# Acad#]
           ,[Escala Inicial]
           ,[Escala Final]
           ,[N° Boletas]
           ,[Valor 1era Boleta]
           ,[Cond# Económica]
           ,[Fecha Recat#]
           ,[Pagantes]
           ,[Fecha Pago de boleta]
           ,[Recogió Cronograma]
           ,[Recogió Horario]
           ,[Fecha Recogió Horario]
           ,[Perdido]
           ,[Fecha de Perdido]
           ,[Motivo Perdido]
           ,[Asesor Inicial]
           ,[Asesor Final]
           ,[Doc# Completos al Inscribirse]
           ,[Sondeo carreras de 3 ó 4 anos]
           ,[Dirección]
           ,[Distrito]
           ,[E-mail]
           ,[Edad]
           ,[Colegio]
           ,[Distrito Colegio]
           ,[Año fin Colegio]
           ,[Pensión Colegio]
           ,[Monto Declarado]
           ,[Otra Institución de Traslado]
           ,[Carrera de procedencia]
           ,[Motivo de traslado]
           ,[File Completo]
           ,[2 fotos tamaño carné]
           ,[Certificado (Original de 1° a 5° de Secundaria)]
           ,[Certificados de los Primeros Puestos (hasta el 5º en toda la sec]
           ,[Constancia de ingreso de Universidad o Instituto de procedencia]
           ,[Constancia de la Federación Nacional de Deporte]
           ,[Copia de DNI o Partida de Nacimiento]
           ,[Syllabus y Certificado de notas Originales de la Institución de ]
           ,[Consentimiento de datos]
           ,[Declaración Jurada]
           ,[Información de Pago del Postulante]
           ,[Solicitud de admisión]
           ,[Traslado]
           ,[Certificado (Original) de 1° a 5° de Secundaria – con promedio i]
           ,[File Completo1]
           ,[Fecha File Completo]
           ,[Fecha pago matrícula]
           ,[Estado Cliente]
           ,[Últ# Contacto]
           ,[Tipo Seguimiento]
           ,[Respuesta]
           ,[Observación]
           ,[Sede Atención]
           ,[Hábil para Pagar]
           ,[Fecha Hábil para Pagar]
           ,[Teléfono]
           ,[Celular]
           ,[Fecha de Procedencia Final]
           ,[Sede Interés]
           ,[Acción]
           ,[Fecha Acción]
           ,[Tipo Contacto]
           ,[Adelanta Curso]
           ,[Asesor registra MyB]
           ,[Adelante Ciclo 0]
           ,[1ra Boleta Fraccionada]
           ,[Observación Colegio]
           ,[Becado 100%]
           ,[Matricula]
           ,[Postulantes]
           ,[Estudio Superior: Univ/Instit]
           ,[Monto Declarado1]
           ,[DNI]
           ,[Promesa Pago]
           ,[NuevoAntiguo]
           ,[Cod# Modular]
           ,[Traslado_LN]
           ,[F_Ent_Cert_1_a_5_Secun]
           ,[Asesor_contacto]
           ,[tipoPrograma]
           ,[Modalidad]
	FROM import_prometeo_pagado_antegrado_data_pre
	WHERE [Id Sisproven] IS NOT NULL AND [Modalidad Inicial] NOT LIKE '%RESERVA%' AND [Pagantes] LIKE '%1%') AS datosnuevos
WHERE NOT EXISTS (SELECT 1 FROM [dbo].[tb_prometeo_pagado_antegrado] AS verificacion WHERE verificacion.[Id Sisproven] = datosnuevos.[Id Sisproven])

END
GO
